language: node_js
node_js:
  - "6"
cache:
  timeout: 500
  directories:
    - node_modules
script:
    - npm run build
notifications:
  email: false
deploy:
    - provider: script
      skip_cleanup: true
      script: node ftpdeploy.js --user ${PERF_FTP_USER} --password ${PERF_FTP_PWD} --use_strict
      on:
        tags: true
        all_branches: true